snc_redis:
    clients:

# Define your clients here. The example below connects to database 0 of the default Redis server.
#
# See https://github.com/snc/SncRedisBundle/blob/master/Resources/doc/index.md for instructions on
# how to configure the bundle.
#
        default:
            type: predis
            alias: default
            dsn: "%env(REDIS_URL)%"
        doctrine:
            type: predis
            alias: doctrine
            dsn: "%env(REDIS_URL)%"
    doctrine:
        metadata_cache:
            client: doctrine
            entity_manager: default
            document_manager: default
        result_cache:
            client: doctrine
            entity_manager: default
        query_cache:
            client: doctrine
            entity_manager: default
